### ISSUE TITLE
accession number of "Processed" header key in sequence entries

### ISSUE THREAD

**Issue by why2kill** [HUPO-PSI/PEFF#2]
Hello,
It seems that the PEFF CV was incorporated into PSI MS CV.
Originally in the PEFF 1.0 draft, the accession number of Processed key was PEFF:1027 and PEFF:1028, one is for signal sequence and the other is mature protein.
However, I cannot find these corresponding items in PSI MS CV.
Are they the terms, [Term] id: PEFF:0001021 and [Term] id: PEFF:0001022, which names are Signal and Transit?
Thanks.

**Comment by why2kill** [comment]
Oh, I reviewed the example in the PEFF 1.0 draft and the value of /Processed term is like (1|40|signal peptide).
So in the current format, the accession number seems not necessary...    Am I right?

**Comment by edeutsch** [comment]
After various discussion, the final implementation will be like this:
\Processed=(1|24|PEFF:0001021|signal peptide)(25|331|PEFF:0001020|mature protein|chain A)(332|355|PEFF:0001034|propeptide)(356|831|PEFF:0001020|mature protein|chain B)
All example files and documentation and CV have been updated to reflect this.
