### ISSUE TITLE
Allow spaces between list items?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/PEFF#4]
Current spec says: There MUST NOT be spaces between items

We have a spec doc page 8 comment regarding list items: Tiny Valid example has the following: \PName=(Nucleolar protein NOP5) (Nucleolar protein 5) (NOP58) i.e. with spaces

Apparently my validator is tolerant of spaces between them.

Shall we fix the examples and the validator to NOT allow these?
Or should we adjust the specification to permit spaces here and require parsers to tolerate them?

What do you think?

**Comment by jim-shofstahl** [comment]
I took a look at the small code that I have for reading a PEFF file isn’t impacted by a space so I would be OK with them in the format.

**Comment by pabinz** [comment]
The reason for this specification is historical. At the time of the original specs, we were thinking that a list might be constrained by not allowing spaces between items of the list. I believe that this constrain could be removed as it does not impact the risk of making mistakes (i.e. all items of a list lays between  \key=   and the next \key= , or the end of the line ).

ð  My suggestion: Adjust the specs and remove the constraint

Pierre-Alain



De : jshofstahl <notifications@github.com>
Envoyé : mercredi 20 juin 2018 07:25
À : HUPO-PSI/PEFF <PEFF@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [HUPO-PSI/PEFF] Allow spaces between list items? (#4)

I took a look at the small code that I have for reading a PEFF file isn’t impacted by a space so I would be OK with them in the format.

**Comment by edeutsch** [comment]
okay, are there any other comments? If not, I will amend the spec to explicitly allow spaces, although they are certainly not necessary or encouraged.

**Comment by edeutsch** [comment]
The spec and validator now permit spaces without warnings
