### ISSUE TITLE
Address PEFF and mzIdentML and mzTab

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/PEFF#6]
On page 5, we say:

For searches performed using a PEFF file, the downstream result in mzIdentML will need to encode a reference to the PEFF file used.

Reviewer says:

Although actually an action point for mzIdentML: have you already checked, whether referencing a PEFF file as database is encodable? Or have you already added a CV term? If Yes, that could be a comment here. (same for mzTab)

How shall we address this?

**Comment by javizca** [comment]
There is already a CV param in the MS-CV for the PEFF format (MS:1001462), a child term of "database file formats".  So, it is perfectly supported.

This is an example taken from a mzIdentML file referencing a FASTA file. Then an analogous mechanism could be used for PEFF.


<SearchDatabase location="file:////usr/local/mascot/sequence/SwissProt/current/SwissProt_2012_06.fasta" id="SDB_SwissProt" name="SwissProt" numDatabaseSequences="536489" numResidues="190389898" version="SwissProt_2012_06.fasta">
        <FileFormat>
          <cvParam accession="MS:1001348" name="FASTA format" cvRef="PSI-MS" />
        </FileFormat>
        <DatabaseName>
          <userParam name="SwissProt_2012_06.fasta" />
        </DatabaseName>
        <cvParam accession="MS:1001073" name="database type amino acid" cvRef="PSI-MS" />
      </SearchDatabase>
